conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
provider:
  linux_aarch64: azure
  osx_arm64: azure
  win_arm64: azure
extra_platforms:
  - linux-aarch64
  - osx-arm64
  - win-arm64
